
version: 2

models:
  - name: customers
    description: "A customers model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: first_name
        description: "The first name of customer"
        data_tests:
          - not_null
      - name: last_name
        description: "The last name of customer"
        data_tests:
          - not_null

  - name: payments
    description: "The payments model"
    columns:
      - name: payment_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
      - name: paymentmethod
        description: "The payment method of the customer"
        data_tests:
          - not_null